export const GET_EPISODES_SUCCESS = 'GET_EPISODES_SUCCESS';
export const GET_EPISODES_FAIL = 'GET_EPISODES_FAIL';
export const GET_EPISODES_LOADING = 'GET_EPISODES_LOADING';
export const GET_EPISODES_LOADED = 'GET_EPISODES_LOADED';